# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 856213a442581d6f248cc050fdd885de364cb665b46deaf4885dbb216cc6f799dfcb68fb8257edb72199cd97646d99655450f5b5129a0494dc641424a9e7b2f1

test:
  secret_key_base: 0ec827e8aff88fff356a4829bcb39ccc5202002fdacfb46f3e547a44016c49be9e57f636c0d2d1ca7e8ffe5137ccab4e430f5ed4e00657f3cef532f707228d5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
